[package]
name = "tera"
version = "0.1.0"
authors = ["BotchM <botchm@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.4"
ic-cdk = "0.3.1"
ic-cdk-macros = "0.3"
ic-kit = "0.4.3"
